CREATE TABLE COMPANY("ID" INTEGER not null primary key, "NAME" VARCHAR(50));
CREATE TABLE COMPANYFOLDER("COMPANYID" INTEGER not null, "FOLDERTYPE" VARCHAR(10) not null, "PATH" VARCHAR(300) not null, PRIMARY KEY("COMPANYID", "FOLDERTYPE"), FOREIGN KEY("COMPANYID") REFERENCES COMPANY("ID"));
