CREATE SEQUENCE COMPANYFILEID START WITH 1000;
CREATE SEQUENCE COMPANYDATAID START WITH 1000;
CREATE TABLE COMPANY("ID" INTEGER not null primary key, "NAME" VARCHAR(50));
CREATE TABLE COMPANYFOLDER("COMPANYID" INTEGER not null, "FOLDERTYPE" VARCHAR(10) not null, "PATH" VARCHAR(300) not null, PRIMARY KEY("COMPANYID", "FOLDERTYPE"), FOREIGN KEY("COMPANYID") REFERENCES COMPANY("ID"));
CREATE TABLE COMPANYFILE("ID" INTEGER not null primary key, "COMPANYID" INTEGER not null, "FILEPATH" VARCHAR(500), FOREIGN KEY("COMPANYID") REFERENCES COMPANY("ID"));
CREATE TABLE COMPANYDATA("ID" INTEGER not null primary key, "COMPANYID" INTEGER not null, "DATA" VARCHAR(200), "DATA2" VARCHAR(200), "DATA3" VARCHAR(200), "DATA4" VARCHAR(200), "DATA5" VARCHAR(200), "DATA6" VARCHAR(200), "DATA7" VARCHAR(200), "DATA8" VARCHAR(200), "DATA9" VARCHAR(200), FOREIGN KEY("COMPANYID") REFERENCES COMPANY("ID"));
